{
  "id": "pic",
    "hash": 1,
      "initialPage": 0,
        "element": null,
          "container": null,
            "canvas": null,
              "overlays": [],
                "overlaysContainer": null,
                  "previousBody": [],
                    "customControls": [],
                      "source": null,
                        "drawer": null,
                          "world": null,
                            "viewport": null,
                              "navigator": null,
                                "collectionViewport": null,
                                  "collectionDrawer": null,
                                    "navImages": {
    "zoomIn": {
      "REST": "zoomin_rest.png",
        "GROUP": "zoomin_grouphover.png",
          "HOVER": "zoomin_hover.png",
            "DOWN": "zoomin_pressed.png"
    },
    "zoomOut": {
      "REST": "zoomout_rest.png",
        "GROUP": "zoomout_grouphover.png",
          "HOVER": "zoomout_hover.png",
            "DOWN": "zoomout_pressed.png"
    },
    "home": {
      "REST": "home_rest.png",
        "GROUP": "home_grouphover.png",
          "HOVER": "home_hover.png",
            "DOWN": "home_pressed.png"
    },
    "fullpage": {
      "REST": "fullpage_rest.png",
        "GROUP": "fullpage_grouphover.png",
          "HOVER": "fullpage_hover.png",
            "DOWN": "fullpage_pressed.png"
    },
    "rotateleft": {
      "REST": "rotateleft_rest.png",
        "GROUP": "rotateleft_grouphover.png",
          "HOVER": "rotateleft_hover.png",
            "DOWN": "rotateleft_pressed.png"
    },
    "rotateright": {
      "REST": "rotateright_rest.png",
        "GROUP": "rotateright_grouphover.png",
          "HOVER": "rotateright_hover.png",
            "DOWN": "rotateright_pressed.png"
    },
    "previous": {
      "REST": "previous_rest.png",
        "GROUP": "previous_grouphover.png",
          "HOVER": "previous_hover.png",
            "DOWN": "previous_pressed.png"
    },
    "next": {
      "REST": "next_rest.png",
        "GROUP": "next_grouphover.png",
          "HOVER": "next_hover.png",
            "DOWN": "next_pressed.png"
    },
    "x1": {
      "REST": "1x_rest.png",
        "GROUP": "1x_grouphover.png",
          "HOVER": "1x_hover.png",
            "DOWN": "1x_pressed.png"
    },
    "x2": {
      "REST": "2x_rest.png",
        "GROUP": "2x_grouphover.png",
          "HOVER": "2x_hover.png",
            "DOWN": "2x_pressed.png"
    },
    "x4": {
      "REST": "4x_rest.png",
        "GROUP": "4x_grouphover.png",
          "HOVER": "4x_hover.png",
            "DOWN": "4x_pressed.png"
    },
    "x10": {
      "REST": "10x_rest.png",
        "GROUP": "10x_grouphover.png",
          "HOVER": "10x_hover.png",
            "DOWN": "10x_pressed.png"
    },
    "x20": {
      "REST": "20x_rest.png",
        "GROUP": "20x_grouphover.png",
          "HOVER": "20x_hover.png",
            "DOWN": "20x_pressed.png"
    },
    "x40": {
      "REST": "40x_rest.png",
        "GROUP": "40x_grouphover.png",
          "HOVER": "40x_hover.png",
            "DOWN": "40x_pressed.png"
    }
  },
  "buttons": null,
    "profiler": null,
      "xmlPath": null,
        "tileSources": [
          {
            "type": "zoomifytileservice",
            "realPath": "11095",
            "width": 111862,
            "height": 48946,
            "tilesUrl": "https://test.hengdaomed.com/wsi/v1/kfb"
          }
        ],
          "tileHost": null,
            "crossOriginPolicy": false,
              "ajaxWithCredentials": false,
                "loadTilesWithAjax": false,
                  "ajaxHeaders": { },
  "panHorizontal": true,
    "panVertical": true,
      "constrainDuringPan": false,
        "wrapHorizontal": false,
          "wrapVertical": false,
            "visibilityRatio": 0.5,
              "minPixelRatio": 0.5,
                "defaultZoomLevel": 0,
                  "minZoomLevel": null,
                    "maxZoomLevel": null,
                      "homeFillsViewer": false,
                        "clickTimeThreshold": 300,
                          "clickDistThreshold": 5,
                            "dblClickTimeThreshold": 300,
                              "dblClickDistThreshold": 20,
                                "springStiffness": 6.5,
                                  "animationTime": 1.2,
                                    "gestureSettingsMouse": {
    "scrollToZoom": true,
      "clickToZoom": true,
        "dblClickToZoom": false,
          "pinchToZoom": false,
            "flickEnabled": false,
              "flickMinSpeed": 120,
                "flickMomentum": 0.25,
                  "pinchRotate": false
  },
  "gestureSettingsTouch": {
    "scrollToZoom": false,
      "clickToZoom": false,
        "dblClickToZoom": true,
          "pinchToZoom": true,
            "flickEnabled": true,
              "flickMinSpeed": 120,
                "flickMomentum": 0.25,
                  "pinchRotate": false
  },
  "gestureSettingsPen": {
    "scrollToZoom": false,
      "clickToZoom": true,
        "dblClickToZoom": false,
          "pinchToZoom": false,
            "flickEnabled": false,
              "flickMinSpeed": 120,
                "flickMomentum": 0.25,
                  "pinchRotate": false
  },
  "gestureSettingsUnknown": {
    "scrollToZoom": false,
      "clickToZoom": false,
        "dblClickToZoom": true,
          "pinchToZoom": true,
            "flickEnabled": true,
              "flickMinSpeed": 120,
                "flickMomentum": 0.25,
                  "pinchRotate": false
  },
  "zoomPerClick": 2,
    "zoomPerScroll": 1.2,
      "zoomPerSecond": 1,
        "blendTime": 0,
          "alwaysBlend": false,
            "autoHideControls": true,
              "immediateRender": false,
                "minZoomImageRatio": 0.9,
                  "maxZoomPixelRatio": 1.1,
                    "smoothTileEdgesMinZoom": 1.1,
                      "iOSDevice": false,
                        "pixelsPerWheelLine": 40,
                          "autoResize": true,
                            "preserveImageSizeOnResize": false,
                              "minScrollDeltaTime": 50,
                                "showSequenceControl": true,
                                  "sequenceControlAnchor": null,
                                    "preserveViewport": false,
                                      "preserveOverlays": false,
                                        "navPrevNextWrap": false,
                                          "showNavigationControl": true,
                                            "navigationControlAnchor": null,
                                              "showZoomControl": true,
                                                "showHomeControl": true,
                                                  "showFullPageControl": true,
                                                    "showRotationControl": false,
                                                      "show1xControl": true,
                                                        "show2xControl": true,
                                                          "show4xControl": true,
                                                            "show10xControl": true,
                                                              "show20xControl": true,
                                                                "show40xControl": true,
                                                                  "controlsFadeDelay": 2000,
                                                                    "controlsFadeLength": 1500,
                                                                      "mouseNavEnabled": true,
                                                                        "showNavigator": false,
                                                                          "navigatorId": null,
                                                                            "navigatorPosition": "BOTTOM_LEFT",
                                                                              "navigatorSizeRatio": 0.2,
                                                                                "navigatorMaintainSizeRatio": false,
                                                                                  "navigatorTop": null,
                                                                                    "navigatorLeft": null,
                                                                                      "navigatorHeight": "150px",
                                                                                        "navigatorWidth": "250px",
                                                                                          "navigatorAutoResize": true,
                                                                                            "navigatorAutoFade": false,
                                                                                              "navigatorRotate": true,
                                                                                                "degrees": 0,
                                                                                                  "opacity": 1,
                                                                                                    "preload": false,
                                                                                                      "compositeOperation": null,
                                                                                                        "placeholderFillStyle": null,
                                                                                                          "showReferenceStrip": false,
                                                                                                            "referenceStripScroll": "horizontal",
                                                                                                              "referenceStripElement": null,
                                                                                                                "referenceStripHeight": null,
                                                                                                                  "referenceStripWidth": null,
                                                                                                                    "referenceStripPosition": "BOTTOM_LEFT",
                                                                                                                      "referenceStripSizeRatio": 0.2,
                                                                                                                        "collectionRows": 3,
                                                                                                                          "collectionColumns": 0,
                                                                                                                            "collectionLayout": "horizontal",
                                                                                                                              "collectionMode": false,
                                                                                                                                "collectionTileSize": 800,
                                                                                                                                  "collectionTileMargin": 80,
                                                                                                                                    "imageLoaderLimit": 0,
                                                                                                                                      "maxImageCacheCount": 200,
                                                                                                                                        "timeout": 30000,
                                                                                                                                          "useCanvas": true,
                                                                                                                                            "prefixUrl": "/static/",
                                                                                                                                              "updateAnnotationCanvas": null,
                                                                                                                                                "debugMode": false,
                                                                                                                                                  "debugGridColor": [
                                                                                                                                                    "#437AB2",
                                                                                                                                                    "#1B9E77",
                                                                                                                                                    "#D95F02",
                                                                                                                                                    "#7570B3",
                                                                                                                                                    "#E7298A",
                                                                                                                                                    "#66A61E",
                                                                                                                                                    "#E6AB02",
                                                                                                                                                    "#A6761D",
                                                                                                                                                    "#666666"
                                                                                                                                                  ],
                                                                                                                                                    "zoomInButton": "zoominbtn",
                                                                                                                                                      "zoomOutButton": "zoomoutbtn",
                                                                                                                                                        "homeButton": "home",
                                                                                                                                                          "fullPageButton": "full",
                                                                                                                                                            "x1Button": "x1",
                                                                                                                                                              "x2Button": "x2",
                                                                                                                                                                "x4Button": "x4",
                                                                                                                                                                  "x10Button": "x10",
                                                                                                                                                                    "x20Button": "x20",
                                                                                                                                                                      "x40Button": "x40",
                                                                                                                                                                        "_sequenceIndex": 0,
                                                                                                                                                                          "_firstOpen": true,
                                                                                                                                                                            "_updateRequestId": null,
                                                                                                                                                                              "_loadQueue": [],
                                                                                                                                                                                "currentOverlays": [],
                                                                                                                                                                                  "_lastScrollTime": 1540430190460,
                                                                                                                                                                                    "events": { }
}





{
  "id": "pic",
    "hash": 1,
      "initialPage": 0,
        "element": null,
          "container": null,
            "canvas": null,
              "overlays": [],
                "overlaysContainer": null,
                  "previousBody": [],
                    "customControls": [],
                      "source": null,
                        "drawer": null,
                          "world": null,
                            "viewport": null,
                              "navigator": null,
                                "collectionViewport": null,
                                  "collectionDrawer": null,
                                    "navImages": {
    "zoomIn": {
      "REST": "zoomin_rest.png",
        "GROUP": "zoomin_grouphover.png",
          "HOVER": "zoomin_hover.png",
            "DOWN": "zoomin_pressed.png"
    },
    "zoomOut": {
      "REST": "zoomout_rest.png",
        "GROUP": "zoomout_grouphover.png",
          "HOVER": "zoomout_hover.png",
            "DOWN": "zoomout_pressed.png"
    },
    "home": {
      "REST": "home_rest.png",
        "GROUP": "home_grouphover.png",
          "HOVER": "home_hover.png",
            "DOWN": "home_pressed.png"
    },
    "fullpage": {
      "REST": "fullpage_rest.png",
        "GROUP": "fullpage_grouphover.png",
          "HOVER": "fullpage_hover.png",
            "DOWN": "fullpage_pressed.png"
    },
    "rotateleft": {
      "REST": "rotateleft_rest.png",
        "GROUP": "rotateleft_grouphover.png",
          "HOVER": "rotateleft_hover.png",
            "DOWN": "rotateleft_pressed.png"
    },
    "rotateright": {
      "REST": "rotateright_rest.png",
        "GROUP": "rotateright_grouphover.png",
          "HOVER": "rotateright_hover.png",
            "DOWN": "rotateright_pressed.png"
    },
    "previous": {
      "REST": "previous_rest.png",
        "GROUP": "previous_grouphover.png",
          "HOVER": "previous_hover.png",
            "DOWN": "previous_pressed.png"
    },
    "next": {
      "REST": "next_rest.png",
        "GROUP": "next_grouphover.png",
          "HOVER": "next_hover.png",
            "DOWN": "next_pressed.png"
    },
    "x1": {
      "REST": "1x_rest.png",
        "GROUP": "1x_grouphover.png",
          "HOVER": "1x_hover.png",
            "DOWN": "1x_pressed.png"
    },
    "x2": {
      "REST": "2x_rest.png",
        "GROUP": "2x_grouphover.png",
          "HOVER": "2x_hover.png",
            "DOWN": "2x_pressed.png"
    },
    "x4": {
      "REST": "4x_rest.png",
        "GROUP": "4x_grouphover.png",
          "HOVER": "4x_hover.png",
            "DOWN": "4x_pressed.png"
    },
    "x10": {
      "REST": "10x_rest.png",
        "GROUP": "10x_grouphover.png",
          "HOVER": "10x_hover.png",
            "DOWN": "10x_pressed.png"
    },
    "x20": {
      "REST": "20x_rest.png",
        "GROUP": "20x_grouphover.png",
          "HOVER": "20x_hover.png",
            "DOWN": "20x_pressed.png"
    },
    "x40": {
      "REST": "40x_rest.png",
        "GROUP": "40x_grouphover.png",
          "HOVER": "40x_hover.png",
            "DOWN": "40x_pressed.png"
    }
  },
  "buttons": null,
    "profiler": null,
      "xmlPath": null,
        "tileSources": [
          {
            "type": "zoomifytileservice",
            "realPath": "11095",
            "width": 111862,
            "height": 48946,
            "tilesUrl": "https://test.hengdaomed.com/wsi/v1/kfb"
          }
        ],
          "tileHost": null,
            "crossOriginPolicy": false,
              "ajaxWithCredentials": false,
                "loadTilesWithAjax": false,
                  "ajaxHeaders": { },
  "panHorizontal": true,
    "panVertical": true,
      "constrainDuringPan": false,
        "wrapHorizontal": false,
          "wrapVertical": false,
            "visibilityRatio": 0.5,
              "minPixelRatio": 0.5,
                "defaultZoomLevel": 0,
                  "minZoomLevel": null,
                    "maxZoomLevel": null,
                      "homeFillsViewer": false,
                        "clickTimeThreshold": 300,
                          "clickDistThreshold": 5,
                            "dblClickTimeThreshold": 300,
                              "dblClickDistThreshold": 20,
                                "springStiffness": 6.5,
                                  "animationTime": 1.2,
                                    "gestureSettingsMouse": {
    "scrollToZoom": true,
      "clickToZoom": true,
        "dblClickToZoom": false,
          "pinchToZoom": false,
            "flickEnabled": false,
              "flickMinSpeed": 120,
                "flickMomentum": 0.25,
                  "pinchRotate": false
  },
  "gestureSettingsTouch": {
    "scrollToZoom": false,
      "clickToZoom": false,
        "dblClickToZoom": true,
          "pinchToZoom": true,
            "flickEnabled": true,
              "flickMinSpeed": 120,
                "flickMomentum": 0.25,
                  "pinchRotate": false
  },
  "gestureSettingsPen": {
    "scrollToZoom": false,
      "clickToZoom": true,
        "dblClickToZoom": false,
          "pinchToZoom": false,
            "flickEnabled": false,
              "flickMinSpeed": 120,
                "flickMomentum": 0.25,
                  "pinchRotate": false
  },
  "gestureSettingsUnknown": {
    "scrollToZoom": false,
      "clickToZoom": false,
        "dblClickToZoom": true,
          "pinchToZoom": true,
            "flickEnabled": true,
              "flickMinSpeed": 120,
                "flickMomentum": 0.25,
                  "pinchRotate": false
  },
  "zoomPerClick": 2,
    "zoomPerScroll": 1.2,
      "zoomPerSecond": 1,
        "blendTime": 0,
          "alwaysBlend": false,
            "autoHideControls": true,
              "immediateRender": false,
                "minZoomImageRatio": 0.9,
                  "maxZoomPixelRatio": 1.1,
                    "smoothTileEdgesMinZoom": 1.1,
                      "iOSDevice": false,
                        "pixelsPerWheelLine": 40,
                          "autoResize": true,
                            "preserveImageSizeOnResize": false,
                              "minScrollDeltaTime": 50,
                                "showSequenceControl": true,
                                  "sequenceControlAnchor": null,
                                    "preserveViewport": false,
                                      "preserveOverlays": false,
                                        "navPrevNextWrap": false,
                                          "showNavigationControl": true,
                                            "navigationControlAnchor": null,
                                              "showZoomControl": true,
                                                "showHomeControl": true,
                                                  "showFullPageControl": true,
                                                    "showRotationControl": false,
                                                      "show1xControl": true,
                                                        "show2xControl": true,
                                                          "show4xControl": true,
                                                            "show10xControl": true,
                                                              "show20xControl": true,
                                                                "show40xControl": true,
                                                                  "controlsFadeDelay": 2000,
                                                                    "controlsFadeLength": 1500,
                                                                      "mouseNavEnabled": true,
                                                                        "showNavigator": false,
                                                                          "navigatorId": null,
                                                                            "navigatorPosition": "BOTTOM_LEFT",
                                                                              "navigatorSizeRatio": 0.2,
                                                                                "navigatorMaintainSizeRatio": false,
                                                                                  "navigatorTop": null,
                                                                                    "navigatorLeft": null,
                                                                                      "navigatorHeight": "150px",
                                                                                        "navigatorWidth": "250px",
                                                                                          "navigatorAutoResize": true,
                                                                                            "navigatorAutoFade": false,
                                                                                              "navigatorRotate": true,
                                                                                                "degrees": 0,
                                                                                                  "opacity": 1,
                                                                                                    "preload": false,
                                                                                                      "compositeOperation": null,
                                                                                                        "placeholderFillStyle": null,
                                                                                                          "showReferenceStrip": false,
                                                                                                            "referenceStripScroll": "horizontal",
                                                                                                              "referenceStripElement": null,
                                                                                                                "referenceStripHeight": null,
                                                                                                                  "referenceStripWidth": null,
                                                                                                                    "referenceStripPosition": "BOTTOM_LEFT",
                                                                                                                      "referenceStripSizeRatio": 0.2,
                                                                                                                        "collectionRows": 3,
                                                                                                                          "collectionColumns": 0,
                                                                                                                            "collectionLayout": "horizontal",
                                                                                                                              "collectionMode": false,
                                                                                                                                "collectionTileSize": 800,
                                                                                                                                  "collectionTileMargin": 80,
                                                                                                                                    "imageLoaderLimit": 0,
                                                                                                                                      "maxImageCacheCount": 200,
                                                                                                                                        "timeout": 30000,
                                                                                                                                          "useCanvas": true,
                                                                                                                                            "prefixUrl": "/static/",
                                                                                                                                              "updateAnnotationCanvas": null,
                                                                                                                                                "debugMode": false,
                                                                                                                                                  "debugGridColor": [
                                                                                                                                                    "#437AB2",
                                                                                                                                                    "#1B9E77",
                                                                                                                                                    "#D95F02",
                                                                                                                                                    "#7570B3",
                                                                                                                                                    "#E7298A",
                                                                                                                                                    "#66A61E",
                                                                                                                                                    "#E6AB02",
                                                                                                                                                    "#A6761D",
                                                                                                                                                    "#666666"
                                                                                                                                                  ],
                                                                                                                                                    "zoomInButton": "zoominbtn",
                                                                                                                                                      "zoomOutButton": "zoomoutbtn",
                                                                                                                                                        "homeButton": "home",
                                                                                                                                                          "fullPageButton": "full",
                                                                                                                                                            "x1Button": "x1",
                                                                                                                                                              "x2Button": "x2",
                                                                                                                                                                "x4Button": "x4",
                                                                                                                                                                  "x10Button": "x10",
                                                                                                                                                                    "x20Button": "x20",
                                                                                                                                                                      "x40Button": "x40",
                                                                                                                                                                        "_sequenceIndex": 0,
                                                                                                                                                                          "_firstOpen": true,
                                                                                                                                                                            "_updateRequestId": null,
                                                                                                                                                                              "_loadQueue": [],
                                                                                                                                                                                "currentOverlays": [],
                                                                                                                                                                                  "_lastScrollTime": 1540430376841
}